"""
riddles.py — riddles for a child, written by hand.

The model was asked first and its Polish riddles were too often wrong ("a
squirrel… isn't an animal", "a monkey has a long nose") or gave the answer
away ("Co to za drzewo?" for "drzewo"). For an 8-year-old a riddle must be
true, so these are fixed: every clue fits, the answer isn't in the text,
"accept" lists the forms a child may say, the hint helps without telling.
"""

# (riddle, accepted answers — the first is the answer, hint)
RIDDLES = [
    ("Mruczy, kiedy jest zadowolony, ma wąsy i łapie myszy.",
     ["kot", "kotek", "kotka", "kocur", "kota"], "Mieszka w wielu domach i lubi spać na kanapie."),
    ("Szczeka, merda ogonem i pilnuje domu.",
     ["pies", "piesek", "psa", "psy", "psiak"], "Mówią, że to najlepszy przyjaciel człowieka."),
    ("Ma bardzo długą szyję i zjada liście z wysokich drzew.",
     ["żyrafa", "żyrafę", "żyrafka"], "Mieszka w Afryce i jest wyższa niż autobus."),
    ("Ma twardą skorupę, chowa w niej głowę i nogi, i chodzi bardzo powoli.",
     ["żółw", "żółwik", "żółwia"], "Może żyć ponad sto lat."),
    ("Ma trąbę, ale nie gra na niej muzyki, i ogromne uszy.",
     ["słoń", "słonik", "słonia"], "To największe zwierzę, które chodzi po lądzie."),
    ("Skacze po drzewach, ma puszysty rudy ogon i zbiera orzechy na zimę.",
     ["wiewiórka", "wiewiórkę", "wiewiórki"], "Często można ją spotkać w parku."),
    ("Daje nam mleko, mówi muuu i pasie się na łące.",
     ["krowa", "krowę", "krówka"], "Mieszka na wsi, w oborze."),
    ("W dzień śpi, w nocy poluje, ma wielkie oczy i woła hu, hu.",
     ["sowa", "sowę", "puchacz", "sówka"], "To ptak."),
    ("Bzyczy, lata od kwiatka do kwiatka i robi miód.",
     ["pszczoła", "pszczółka", "pszczołę"], "Mieszka w ulu."),
    ("Ma kolorowe skrzydła, a zanim nauczył się latać, był gąsienicą.",
     ["motyl", "motylek", "motyla"], "Lubi słoneczne łąki pełne kwiatów."),
    ("Zielona, skacze po trawie i kumka w stawie.",
     ["żaba", "żabka", "żabę"], "Kiedy była mała, pływała jako kijanka."),
    ("Świeci w dzień na niebie i grzeje, a wieczorem chowa się za horyzontem.",
     ["słońce", "słoneczko"], "Bez niego byłoby ciemno i zimno."),
    ("Kapie z chmur, a po nim robią się kałuże.",
     ["deszcz", "deszczyk"], "Bierzemy wtedy parasol."),
    ("Jest biały i zimny, pada zimą, a można z niego ulepić bałwana.",
     ["śnieg", "śnieżek"], "Topi się, kiedy robi się ciepło."),
    ("Nocą wędruje po niebie: raz jest okrągły, a raz cienki jak rogalik.",
     ["księżyc", "księżyca"], "Po łacinie nazywa się tak jak ja!"),
    ("Mruga na nocnym niebie i jest ich tyle, że nie da się ich policzyć.",
     ["gwiazda", "gwiazdy", "gwiazdka", "gwiazdki"], "Jedną z nich jest Słońce."),
    ("Ma wskazówki, ale nie pokazuje drogi. Tyka i mówi, która godzina.",
     ["zegar", "zegarek"], "Wisi na ścianie albo nosisz go na ręce."),
    ("Ma zęby, ale nie gryzie. Czeszesz nim włosy.",
     ["grzebień", "grzebyk", "grzebienia"], "Leży zwykle w łazience."),
    ("Ma cztery nogi, ale nigdzie nie chodzi. Jemy przy nim obiad.",
     ["stół", "stolik", "stołu"], "Stoi w kuchni albo w jadalni."),
    ("Ma szyjkę, ale nie ma głowy. Nalewa się z niej sok albo wodę.",
     ["butelka", "butelkę", "butla"], "Może być szklana albo plastikowa."),
    ("Ma strony, ale nie ma drzwi, ma okładkę, ale nie jest kocem. Czytasz ją.",
     ["książka", "książkę", "książeczka", "książeczkę"], "Stoi na półce."),
    ("Ma koła i pedały, ale nie ma silnika. Trzeba na nim utrzymać równowagę.",
     ["rower", "rowerek", "rowerze"], "Jeździsz na nim po ścieżce, w kasku."),
    ("Ma ogon, ale nie jest zwierzęciem. Fruwa na sznurku, kiedy wieje wiatr.",
     ["latawiec", "latawca", "latawce"], "Puszcza się go jesienią na łące."),
    ("Jest żółty, wygięty jak uśmiech, a zanim go zjesz, trzeba zdjąć skórkę.",
     ["banan", "banana", "banany"], "To owoc, który uwielbiają małpy."),
    ("Z wierzchu zielony, w środku czerwony, z czarnymi pestkami. Jemy go latem.",
     ["arbuz", "arbuza"], "Jest duży, ciężki i bardzo soczysty."),
    ("Pomarańczowa, rośnie pod ziemią i bardzo lubią ją króliki.",
     ["marchewka", "marchew", "marchewkę"], "To warzywo."),
    ("Rośnie na drzewie, bywa czerwone albo zielone, a robi się z niego szarlotkę.",
     ["jabłko", "jabłuszko", "jabłka"], "Rośnie w sadzie."),
    ("Nosi kapelusz, choć nie ma głowy. Rośnie w lesie po deszczu.",
     ["grzyb", "grzybek", "grzyby", "borowik", "muchomor"], "Zbiera się go do koszyka."),
    ("Im więcej z niej wykopiesz, tym większa się robi.",
     ["dziura", "dziurę", "dołek", "dół"], "Kopie się ją łopatą."),
    ("Ma klawisze, ale nie otwiera nimi drzwi. Gra się na nim muzykę.",
     ["pianino", "fortepian", "keyboard", "pianina"], "To instrument."),
    ("Kiedy go włączysz, w pokoju robi się jasno.",
     ["lampa", "lampka", "światło", "żarówka"], "Wisi pod sufitem albo stoi na biurku."),
]
